[package]
name = "tari-core-native"
version = "0.1.0"
edition = "2021"
authors = ["Tari Development Team"]
license = "BSD-3-Clause"

[lib]
name = "tari_core_native"
crate-type = ["cdylib"]

[dependencies]
neon = { version = "0.10", default-features = false, features = ["napi-6"] }
once_cell = "1.19"
libc = "0.2"
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
dirs-next = "1.0"
# Real Tari dependencies from development branch
tari_core = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_common = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_comms = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_crypto = { version = "0.22.0" }
tari_key_manager = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_storage = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_common_types = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_script = { git = "https://github.com/tari-project/tari.git", branch = "development" }
tari_utilities = { version = "0.8" }
tari_p2p = { git = "https://github.com/tari-project/tari.git", branch = "development" }

# Minotari wallet dependencies  
minotari_wallet = { git = "https://github.com/tari-project/tari.git", branch = "development" }

# Additional dependencies for production features
lazy_static = "1.4"
uuid = { version = "1.0", features = ["v4"] }
toml = "0.8"
tempfile = "3.0"
num_cpus = "1.0"
hex = "0.4"
trust-dns-resolver = "0.23"
bip39 = "2.0"

[build-dependencies]
neon-build = "0.10"

[profile.release]
opt-level = 3
lto = true
strip = false

# Platform-specific dependencies
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }
